devel: static checks: Integrate build(); add lintian() as extra check.

diff --git a/devel b/devel
--- a/devel
+++ b/devel
@@ -208,17 +208,23 @@ mbd_check:static:0:codespell()
 	fi
 }
 
-mbd_check:static:1:pydoctests()
+mbd_check:static:0:css()
 {
-	(
-		pyenv
-		for m in $(mbd_pymodules ./setup.py ./doc/conf.py); do  # ./setup.py && ./doc/conf.py can't be used for doctests
-			local module="$(basename $(tr '/' '.' <<< ${m:4}) '.py' | cut -d. -f2-)"
-			printf "=> Doctest on %s (%s)\n" "${m}" "${module}"
-			( cd ./src/ && ./run-doctest "${module}" )
-		done
-		python3 -m doctest -v src/mini-buildd src/mini-buildd-tool
-	)
+	local class errors=0 ignoreRegex="mbd-action-.*"
+
+	for class in $(grep -h -o "#mbd[[:alnum:]\-]\+" src/mini_buildd/static/css/*.css | sort -r | uniq); do
+		if [[ ${class:1} =~ ${ignoreRegex} ]]; then
+			printf "Skipping %s.\n" "${class}"
+		else
+			if ! grep -r -q "${class:1}" src/mini_buildd/templates/; then
+				printf "E: CSS class unused: %s:\n" "${class}" >&2
+				grep -l "${class}" src/mini_buildd/static/css/*.css
+				errors+=1
+			fi
+		fi
+	done
+	printf "CSS: %s unused classes found.\n" "${errors}"
+	return ${errors}
 }
 
 mbd_check:static:0:pyflakes()
@@ -243,26 +249,36 @@ mbd_check:static:1:pylint()
 	)
 }
 
-mbd_check:static:0:css()
+mbd_check:static:1:pydoctests()
 {
-	local class errors=0 ignoreRegex="mbd-action-.*"
-
-	for class in $(grep -h -o "#mbd[[:alnum:]\-]\+" src/mini_buildd/static/css/*.css | sort -r | uniq); do
-		if [[ ${class:1} =~ ${ignoreRegex} ]]; then
-			printf "Skipping %s.\n" "${class}"
-		else
-			if ! grep -r -q "${class:1}" src/mini_buildd/templates/; then
-				printf "E: CSS class unused: %s:\n" "${class}" >&2
-				grep -l "${class}" src/mini_buildd/static/css/*.css
-				errors+=1
-			fi
-		fi
-	done
-	printf "CSS: %s unused classes found.\n" "${errors}"
-	return ${errors}
+	(
+		pyenv
+		for m in $(mbd_pymodules ./setup.py ./doc/conf.py); do  # ./setup.py && ./doc/conf.py can't be used for doctests
+			local module="$(basename $(tr '/' '.' <<< ${m:4}) '.py' | cut -d. -f2-)"
+			printf "=> Doctest on %s (%s)\n" "${m}" "${module}"
+			( cd ./src/ && ./run-doctest "${module}" )
+		done
+		python3 -m doctest -v src/mini-buildd src/mini-buildd-tool
+	)
 }
 
-mbd_check:static:2:debrepro()
+mbd_check:static:2:build()
+{
+	_head "Checking changelog (must be unchanged)..."
+	git diff-index --exit-code HEAD debian/changelog
+	trap "git checkout debian/changelog" EXIT
+
+	_head "Building snapshot..."
+	gbp dch --snapshot --auto
+	DEB_BUILD_OPTIONS+=" nocheck" gbp buildpackage --git-ignore-new --git-ignore-branch -us -uc
+}
+
+mbd_check:static:3:lintian()
+{
+	lintian --fail-on-warnings --suppress-tags=changelog-should-mention-nmu,source-nmu-has-incorrect-version-number,newer-standards-version --info ../mini-buildd_$(dpkg-parsechangelog --show-field=Version)_$(dpkg --print-architecture).changes
+}
+
+mbd_check:static:9:debrepro()
 {
 	debrepro
 }
@@ -313,7 +329,7 @@ mbd_check()
 # Special to be used in debian/rules
 mbd_check:debian-rules()
 {
-	mbd_check static:1:pydoctests
+	mbd_check:static:1:pydoctests
 }
 
 mbd_service()
@@ -343,14 +359,6 @@ mbd_purge()
 
 mbd_install()
 {
-	_head "Checking changelog (must be unchanged)..."
-	git diff-index --exit-code HEAD debian/changelog
-	trap "git checkout debian/changelog" EXIT
-
-	_head "Building snapshot..."
-	gbp dch --snapshot --auto --ignore-branch
-	gbp buildpackage --git-ignore-new --git-ignore-branch -us -uc --git-postbuild='lintian --info --suppress-tags=changelog-should-mention-nmu,source-nmu-has-incorrect-version-number,newer-standards-version --fail-on-warnings $GBP_CHANGES_FILE'
-
 	_head "Installing snapshot..."
 	cat ./devel.debconf.selections | sudo debconf-set-selections --verbose -
 	sudo debi --with-depends
@@ -358,7 +366,7 @@ mbd_install()
 
 mbd_update()
 {
-	export DEB_BUILD_OPTIONS+=" nocheck"
+	mbd_check:static:2:build
 	mbd_install
 	mbd_service restart
 	printf "Ok, updated (NO checks).\n"
